### ISSUE TITLE
Boilerplate

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/armorbot#1]
# Motivation
We want to set up all the necessary dependencies to get up and going.

# Task Implementation
- [x] Set up project.
- [x] Download all the necessary dependencies.
- [x] Get up all the necessary setup files.
- [x] Set up basic commands.
- [x] Get the web local web server up and running.
- [x] Deploy to Heroku.
