### ISSUE TITLE
Back up the strike menu functionality with unit tests

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/armorbot#10]
# Motivation
We want to make sure that our strike menu components work at a unit level.

# Task Implementation
- [ ] Re-familiarize with testing modules
- [ ] Create scenarios to test
- [ ] Write the tests
- [ ] Verify the inputs and results are as desired.
