### ISSUE TITLE
Replace current token storage with JWT

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/armorbot#12]
# Motivation
We want to replace the current token holding and middleware functions with JWT.

# Task Implementation
- [x] Learn JWT
- [x] Get JWT
- [x] Work with the current login mechanism to be able to store a payload instead of the user's actual OAUTH information
- [x] On a fresh access, access the login route to return a token.
- [x] On an access that already has the token on localstorage, be able to return the user credentials.
- [x] On an expired or revoked access, be able to reset the login state.
- [x] On a logout, remove the token from localstorage and revoke the OUATH token.
- [x] Make sure that the token works both on the hashrouter and the browser router.
- [x] Be able to use the token authorization on the routes instead of a middleware function.
- [x] Delegate some utility or reused functions to a utilities module.
- [x] Move all profile getting from the user to the server instead of the client.
- [x] Verify that all of this works locally.
- [x] Verify that all of this works on heroku
- [x] Unit test the authorization.
