### ISSUE TITLE
User Can Login Securely Using Discord OATH2 and Argon2

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/armorbot#3]
# Motivation
We want to be able to allow the user to login to the dashboard using Discord and the Argon2 hash to securely log in the user. 

# Task Implementation
- [x] Set up the mongodb database.
- [x] Set up the mechanism to which the user can Make a request to OAUTH themselves to discord.
- [x] Make sure that on a successful OAUTH login, the user re-directed back to the page with the 
information updated.
- [x] Be able to store the token to the session.
- [x] Be able to detect that the user has logged in.
- [x] Register an email account for this service.
- [x] Get the google Gmail API key. 
- [x] Create a unique function that mixes in both the OAUTH grant and the user's unique identification. 
- [x] Be able to hash this function in argon2.
- [x] Be able to store the hash into the database.
- [x] Be able to revoke access to the application when the token is expired. 
- [x] Make sure that the database correctly refreshes the hash instance on an expired or invalid token.
