### ISSUE TITLE
User Can Add Bot to a Server

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/armorbot#5]
# Task Implementation
We want to from the dashboard, be able to add the bot to a server.

# Task Implementation
- [x] Create a component that displays all the servers that the user has once the user is fully permissed into the app. 
- [x] On a selection, be able trigger an event to check if the bot is on that server.
- [x] If the bot is not on that server, then change the URL to a bot authorization.
- [x] Otherwise, do nothing.
