### ISSUE TITLE
User can see basic statistics of a server on a bot-placed server. 

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/armorbot#6]
# Motivation
We want to be able to see basic page statistics for a server in which we have placed a bot in. 

# Task Implementation
- [x] Be able to serve middleware to server pages.
- [x] Be able to route on a valid login session, the server page so that the user can possibly bookmark the resource.
- [x] Make sure that the dropdown also properly follows the value of the server page.
- [x] Make sure that the dropdown changes the url if the bot is on the server instead of requesting the bot to add the server. 
- [x] Make sure that the value changes on the dropdown only register on an explicit click or an enter keypress rather than any value change. 
- [x] Make sure that the server can handle the middleware functions for requests to server pages.
- [x] Test the app by hitting the page as a server request, as well as going back and forth.
