### ISSUE TITLE
User can CRUD strikes from server.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/armorbot#9]
# Motivation
We want to be able to create, read, update and delete strikes from users on a server.

# Task Implementation
- [x] If the server entry for user strikes is not on the server, add it. 
- [x] Privatize the view of the page. If the user does not have authorization then the page should return an error. 
- [x] Require the request route to be in the format of origin/server.id/strikes
- [x] Require the user Id and the session token. for any request sent.
- [x] Register middleware for this route. Consider using JSON web tokens. 
- [x] Consider enabling the hashrouter to be able to switch views between the strikes and the serverpage homepage.
